### PR TITLE
correct line number

### PR DESCRIPTION
**Pull request by Truoris**
The line number isn't in the right cell.

### CODE REVIEW

**Comment by tterrag1098** [comment]
:1+: noticed this mistake almost immediately. Easy fix too :(

**Comment by chrisboulton** [comment]
Thanks!

**Comment by tterrag1098** [comment]
Wow, a response to a 2 year old issue in 1 minute. Impressive (?)

**Comment by chrisboulton** [comment]
Missed notifications on GitHub, etc :)

**Pull request merged**
